/**
 * REAL P&ID SYMBOLS — SOURCED FROM THE FULL STENCIL LIBRARY.
 *
 * This file used to hand-convert seven draw.io stencils, reading each shape's
 * mxGraph XML and re-laying it into a 32x32 cell. That was right when seven
 * symbols were all that was in reach. The full converted library is now
 * available — 478 P&ID and 527 electrical stencils at
 * new_material_source/asset_icons_drawio, catalogued in
 * DRAWIO_ASSET_REGISTRY.md — so these seven are no longer approximations. They
 * delegate to `./drawio-glyphs.tsx`, generated by
 * `scripts/build-drawio-glyphs.mjs`.
 *
 * GEOMETRY IS UNCHANGED FOR BOTH LIVE CALLERS, checked rather than assumed. The
 * generator fits every stencil into the same 22-unit live area (x/y 5..27) this
 * file established, so `InstrumentBubble` lands at r=11.0 centred on (16,16) —
 * identical to the hand-drawn ellipse it replaces — and `Vessel` keeps the same
 * open-topped container outline.
 *
 * ── COLOUR IS THE CALLER'S, AND THAT IS THE POINT ────────────────────────────
 *
 * These are PURE PASSTHROUGHS. They deliberately paint no colour, where the old
 * hand-drawn versions hardcoded `stroke={MUTED}` on every path.
 *
 * Every generated glyph strokes `currentColor`, which resolves through the
 * inherited `color` property. So a caller sets a token with an ordinary text
 * class on any ancestor — `text-muted-foreground`, `text-border` — and it simply
 * works. If this file forced a default, that default would sit CLOSER to the
 * glyph than the caller's wrapper and would win, which is exactly why it forces
 * nothing. Each caller states the token it wants at its own call site.
 *
 * This removes a whole bug class. The old arrangement carried `stroke` as a
 * PRESENTATION ATTRIBUTE on each child, and a presentation attribute beats a
 * value inherited from an ancestor — it loses only to a CSS rule matching the
 * same element. So `stroke-border` on a wrapping `<g>` was silently inert, which
 * shipped live in `Rule.tsx` and had to be worked around with a descendant
 * variant (`[&_ellipse]:stroke-border`) that would itself break the moment a
 * symbol stopped being an `<ellipse>`. Inheritance through `color` has no such
 * trap.
 *
 * STROKE WEIGHT IS THE GENERATOR'S, NOT THE CALLER'S. Each glyph sits inside a
 * `<g transform="scale(…)">`, so a stroke-width authored in the 32-unit cell
 * would be scaled by that transform and land wrong — the generator therefore
 * pre-divides by each glyph's own scale to hit a uniform 1.3 cell-weight. DO NOT
 * re-override stroke-width at a call site: it is interpreted in the stencil's
 * local coordinate space, not the cell's, and thins by roughly 4x. Change
 * `TARGET_STROKE` in the generator if the weight needs to move.
 *
 * Licensing, unchanged: geometry originates in draw.io's `stencils/pid` set
 * (github.com/jgraph/drawio, Apache-2.0), per docs/OXOT-DIAGRAMMING-SPEC.md
 * §2.1's "adopt, don't hand-draw" guidance. Apache-2.0 permits this outright;
 * the one restriction in `stencils/LICENSE` bars use inside Atlassian
 * marketplace products, which does not apply to OXOT as a standalone site.
 *
 * No text/label sub-elements are carried over. ISA identifies an instrument by
 * the letter code inside its bubble, so the plain bubbles are interchangeable
 * circles by construction — render the tag letters over one if a reader must
 * tell it from another.
 */
import {
  Vessel,
  InstrumentBubble,
  GateValve,
  CheckValve,
  GlobeValve,
  CentrifugalPump,
  HeatExchanger
} from "./drawio-glyphs";

export {
  Vessel,
  InstrumentBubble,
  GateValve,
  CheckValve,
  GlobeValve,
  CentrifugalPump,
  HeatExchanger
};

/** Named export set, mirroring `ASSET_GLYPHS`/`VIEW_GLYPHS`'s map convention.
 *  For anything beyond these seven, import `./drawio-glyphs` directly — it
 *  carries 43 symbols and grows by editing the generator's curated list. */
export const PID_SYMBOLS = {
  vessel: Vessel,
  instrumentBubble: InstrumentBubble,
  gateValve: GateValve,
  checkValve: CheckValve,
  globeValve: GlobeValve,
  centrifugalPump: CentrifugalPump,
  heatExchanger: HeatExchanger
} as const;
